apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      nodeSeletor:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: busybox
        image: busybox:1.36
        command: ["/bin/sh"]
        args: ["-c", "sleep 3600"]
        volumeMounts:
        - name: data
          mountPath: /mnt/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: test-pvc
