apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: ibm-spectrum-scale-sample
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
